# Generated by Django 2.2.27 on 2022-02-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridients',
            options={'verbose_name': 'ингридиент', 'verbose_name_plural': 'ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
