# Generated by Django 2.2.27 on 2022-02-17 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0002_auto_20220217_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Receipts',
        ),
    ]
